/* This file is automatically generated by NRPy+. Do not edit. */

/* EVOLVED VARIABLES: */
#define NUM_EVOL_GFS 27
#define RTRACEGF	0
#define ADD00GF	1
#define ADD01GF	2
#define ADD02GF	3
#define ADD11GF	4
#define ADD12GF	5
#define ADD22GF	6
#define ALPHAGF	7
#define BETU0GF	8
#define BETU1GF	9
#define BETU2GF	10
#define CFGF	11
#define HDD00GF	12
#define HDD01GF	13
#define HDD02GF	14
#define HDD11GF	15
#define HDD12GF	16
#define HDD22GF	17
#define LAMBDAU0GF	18
#define LAMBDAU1GF	19
#define LAMBDAU2GF	20
#define TRKGF	21
#define UUGF	22
#define VETU0GF	23
#define VETU1GF	24
#define VETU2GF	25
#define VVGF	26


 /* AUXILIARY VARIABLES: */
#define NUM_AUX_GFS 1
#define HGF	0


/* PARITY TYPES FOR EVOLVED VARIABLES.
   SEE "Tutorial-Start_to_Finish-BSSNCurvilinear-Two_BHs_Collide.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[27] = { 0, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 1, 2, 3, 0, 0, 1, 2, 3, 0 };
